version: "3.9"
services:
  drupal:
    image: drupal:8-apache
    network_mode: bridge
    ports:
      - 8080:80
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites

  postgres:
    image: postgres:10
    network_mode: bridge
    environment:
      POSTGRES_PASSWORD: example
